### ISSUE TITLE
CSS issue on `master` branch

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/cb-v2-scratch#301]
The culprit:
```position: absolute
bottom: 0px```
![screen shot 2016-10-08 at 10 02 25 am](https://cloud.githubusercontent.com/assets/4512699/19214718/e1f598fe-8d3e-11e6-8154-bbc8978e7c0e.jpg)

**Comment by dantesolis** [comment]
I can work on this If no one has it yet

**Comment by lpatmo** [comment]
@dantesolis It's yours! I'll put the `claimed` label on this. Please let us know if you have any questions from contributing.md. Thanks!

**Comment by dantesolis** [comment]
thanks @lpatmo. I'll get to it.

**Comment by dantesolis** [comment]
Hey guys running the master branch on my machine but I don't see any bug. The footer is at the bottom as it should. Can someone confirm?  Thanks

**Comment by lpatmo** [comment]
@dantesolis Sorry, can you `git pull`? The footer is broken in the non-logged-in home page view, but fixed on the `localhost:3000/browse` link. Thanks!

**Comment by wuworkshop** [comment]
hi @dantesolis, I'm assuming you're working off of your own fork of the CB repo. Do you have the original CB repo set up as the `upstream` branch? See Github's instructions here on how to add it:

https://help.github.com/articles/configuring-a-remote-for-a-fork/

Then sync your fork by following these instructions:

https://help.github.com/articles/syncing-a-fork/

**Comment by dantesolis** [comment]
@lpatmo & @wuworkshop thanks for the headsup, I actually had forgotten to do the `git fetch upstream` & `git merge upstream/master`

Just did that. However, right now getting a `TypeError: Cannot call method 'toLowerCase' of undefined` the  moment I try to run the app??

This is the full error stack trace:

```
seed data removed
Kadira: completed instrumenting the app

/Users/DS/.meteor/packages/meteor-tool/.1.3.2_4.ozrb6n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
						throw(ex);
						      ^
TypeError: Cannot call method 'toLowerCase' of undefined
    at Object.later.parse.text (/Users/DS/.meteor/packages/percolate_synced-cron/.1.3.0.oxl71a++os+web.browser+web.cordova/npm/node_modules/later/later.js:1506:34)
    at Object.schedule (server/cron_job/methods.js:62:25)
    at scheduleEntry (packages/percolate_synced-cron/packages/percolate_synced-cron.js:110:1)
    at packages/percolate_synced-cron/packages/percolate_synced-cron.js:147:1
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at packages/percolate_synced-cron/packages/percolate_synced-cron.js:146:1
    at /Users/DS/Code/projects/OpenSource/cb-v2-scratch/.meteor/local/build/programs/server/boot.js:290:5
Exited with code: 8
Your application is crashing. Waiting for file change.
```

**Comment by abhiii5459** [comment]
@dantesolis When you do a "git diff" do you see your changed file?

**Comment by dantesolis** [comment]
@abhiii5459 no changes when doing `git diff`and this is the output for `git remote`:

```
codebuddiesdotorg	https://github.com/codebuddiesdotorg/cb-v2-scratch.git (fetch)
codebuddiesdotorg	https://github.com/codebuddiesdotorg/cb-v2-scratch.git (push)
origin	git@github.com:dantesolis/cb-v2-scratch.git (fetch)
origin	git@github.com:dantesolis/cb-v2-scratch.git (push)
upstream	git@github.com:codebuddiesdotorg/cb-v2-scratch.git (fetch)
upstream	git@github.com:codebuddiesdotorg/cb-v2-scratch.git (push)
```

**Comment by dantesolis** [comment]
So the above error when away after doing `meteor reset`,

But now getting this one:

```

seed data removed
Kadira: completed instrumenting the app

/Users/DS/.meteor/packages/meteor-tool/.1.3.2_4.ozrb6n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
						throw(ex);
						      ^
Error: Match error: Expected string, got undefined in field username
    at exports.check (packages/check/match.js:34:1)
    at _createUser (packages/accounts-password/password_server.js:972:3)
    at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1067:10)
    at server/main.js:31:25
    at /Users/DS/Code/projects/OpenSource/cb-v2-scratch/.meteor/local/build/programs/server/boot.js:290:5
Exited with code: 8
Your application is crashing. Waiting for file change.
```

**Comment by dantesolis** [comment]
Never mind, it was a stupid mistake was running it with `meteor run` instead of `meteor --settings settings-development.json`

**Comment by lpatmo** [comment]
Merged in the fix from @dantesolis!
